# the ID or name of the model that is selected by default on launch
default_model = "ollama/llama3.3:latest"
# the system prompt on launch
system_prompt = "You are a helpful assistant, your name is Jarvis, who talks like Jarvis from Ironman with a very polite English Language, and you will address me with a welcome message only at begnning like welcome Sir!, and you will address me frequently as Sir."

# choose from "nebula", "cobalt", "twilight", "hacker", "alpine", "galaxy", "nautilus", "monokai", "textual"
theme = "monokai"
# Set the custom theme
#theme = "example"
# change the syntax highlighting theme of code in messages
# choose from https://pygments.org/styles/
# defaults to "monokai", "github-dark", "lightbulb", "xcode"
message_code_theme = "github-dark"

# example of adding local llama3 support
# only the `name` field is required here.
[[models]]
name = "ollama/llama3.3:latest"



