# Nightfox Wezterm Colors
# Style: nordfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nordfox/nightfox_wezterm.toml
[colors]
# foreground = "#b9bfca"
# background = "#2d333b"
# cursor_bg = "#f0d399"
# cursor_border = "#b9bfca"
# cursor_fg = "#2e3440"
# selection_bg = "#2d333b"
# selection_fg = "#b9bfca"
# ansi = ["#2d333b", "#bf616a", "#a3be8c", "#ebcb8b", "#81a1c1", "#b48ead", "#88c0d0", "#e5e9f0"]
# brights = ["#2d333b", "#d06f79", "#b1d196", "#f0d399", "#8cafd2", "#c895bf", "#93ccdc", "#e7ecf4"]
# compose_cursor = "#f0d399"

# (Github Dark Dimmed) Colors for Wezterm

background = '#2d333b'
foreground = '#adbac7'

cursor_bg = '#adbac7'
cursor_border = '#adbac7'
cursor_fg = '#22272e'

selection_bg = '#2e4c77'
selection_fg = '#adbac7'

ansi = [
    '#2d333b',
    '#FF495C',
    '#539bf5',
    '#F4D58D',
    '#539bf5',
    '#F9B4ED',
    '#539bf5',
    '#909dab',
]
brights = [
    '#2d333b',
    '#ff938a',
    '#6cb6ff',
    '#F4D58D',
    '#6cb6ff',
    '#F9B4ED',
    '#6cb6ff',
    '#cdd9e5',
]
[metadata]
name = 'github_dimmed'
#origin_url = 'https://github.com/edeneast/nightfox.nvim/raw/main/extra/nordfox/nightfox_wezterm.toml'
#origin_url = 'https://github.com/projekt0n/github-theme-contrib/tree/main/themes/wezterm'
